### ISSUE TITLE
Two logos?

### ISSUE THREAD

**Issue by goldfirere** [haskellfoundation/haskellfoundation.github.io#90] opened 2021-07-19 21:09 UTC
The website features a logo in the header (the Haskell logo redesigned to feature an F) and a logo in the footer (the Haskell logo followed by a separate F). Is it intentional to have two similar-but-different logos? I think I'd prefer one (the one in the header), used consistently.

**Comment by elland** [comment] 2021-07-20 09:29
Related to #47.

@emilypi seems to like it :sweat_smile:

**Comment by myShoggoth** [comment] 2021-08-06 15:05
I'm going to close this as a duplicate of #47 and work on that today.

**Closed by myShoggoth** 2021-08-06 15:05 UTC
